#!/usr/bin/env python3
"""Solver-portfolio driver for formal_depth/ (see formal_depth/README.md).

Every job in jobs.py is expanded into one sby task per engine, so that a Slurm
array can run the whole portfolio in parallel (one solver per array task).

  portfolio.py plan WORK [--only REGEX] [--class CLS]
      write WORK/tasks-<CLS>.tsv and WORK/sby/<task>.sby
  portfolio.py run WORK CLS INDEX
      run line INDEX of WORK/tasks-<CLS>.tsv (what the Slurm array calls);
      writes WORK/results/<task>.json
  portfolio.py summarize WORK [--tsv OUT] [--curves OUT]
      one row per task (status, wall time, deepest step, expectation met),
      plus per-step timestamps (depth vs time) for BMC/induction runs

Environment (defaults in jobs.py): FD_SNAP (exported 73536f0 tree),
FD_RTL (its formal/run.sh --generate-only output), FD_FDRTL (generate_fd
output), SBY_BIN (directory holding sby).
"""
import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import jobs as J  # noqa: E402


def slug(engine):
    return re.sub(r"[^A-Za-z0-9]+", "-", engine).strip("-")


def expand(only=None, cls=None, engine_re=None):
    tasks = []
    for job in J.JOBS:
        if only and not re.search(only, job["name"]):
            continue
        if cls and job.get("cls", "light") != cls:
            continue
        for engine in job["engines"]:
            if engine_re and not re.search(engine_re, engine):
                continue
            tasks.append((f"{job['name']}@{slug(engine)}", job, engine))
    return tasks


def sby_text(job, engine):
    opts = [f"mode {job['mode']}", f"depth {job['depth']}"]
    if job.get("expect", "PASS") == "FAIL":
        opts.append("expect fail")
    opts += job.get("options", [])
    files = [J.path(f) for f in job["files"]]
    for f in files:
        if not os.path.exists(f):
            raise SystemExit(f"portfolio: missing file {f}")
    return "\n".join(
        ["# generated by formal_depth/portfolio.py; job " + job["name"],
         "[options]", *opts, "", "[engines]", engine, "", "[script]",
         *job["script"], "", "[files]", *files, ""])


def cmd_plan(args):
    os.makedirs(os.path.join(args.work, "sby"), exist_ok=True)
    classes = {}
    for name, job, engine in expand(args.only, args.cls, args.engine):
        with open(os.path.join(args.work, "sby", name + ".sby"), "w") as f:
            f.write(sby_text(job, engine))
        classes.setdefault(job.get("cls", "light"), []).append(
            (name, job["name"], engine, job["mode"], str(job["depth"]),
             job.get("expect", "PASS"), str(args.timeout or job.get("timeout", J.DEFAULT_TIMEOUT))))
    for cls, rows in classes.items():
        path = os.path.join(args.work, f"tasks-{cls}.tsv")
        with open(path, "w") as f:
            for r in rows:
                f.write("\t".join(r) + "\n")
        print(f"{path}: {len(rows)} tasks")


STEP = re.compile(r"##\s+(\d+):(\d+):(\d+)\s+(Checking assertions|Trying induction|"
                  r"Checking cover reachability) in step (\d+)")
ABC_FRAME = re.compile(r"^SBY\s+(\d+):(\d+):(\d+) \[[^]]*\] engine_\d+: (\d+) \+ : Var =", re.M)
SBY_TIME = re.compile(r"^SBY\s+(\d+):(\d+):(\d+) ", re.M)


def parse_log(text):
    """Extract per-step start times (seconds since the solver started)."""
    base, ind = {}, {}
    for m in STEP.finditer(text):
        secs = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3))
        target = ind if m.group(4) == "Trying induction" else base
        step = int(m.group(5))
        target.setdefault(step, secs)
    # abc bmc3 prints one line per completed frame; time it with sby's clock
    # (seconds since the first sby log line, wrapping at midnight).
    frames = {}
    first = SBY_TIME.search(text)
    if first:
        t0 = int(first.group(1)) * 3600 + int(first.group(2)) * 60 + int(first.group(3))
        for m in ABC_FRAME.finditer(text):
            t = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3))
            frames.setdefault(int(m.group(4)), (t - t0) % 86400)
    status = None
    for m in re.finditer(r"DONE \(([A-Z]+), rc=(\d+)\)", text):
        status = m.group(1)
    return base, ind, frames, status


FAILED = re.compile(r"failed assertion (\S+) at ([\w.]+\.(?:sv|vh)):(\d+)")
FAILED_ALT = re.compile(r"Assert failed in \w+: (?:(\w+) \()?([\w.]+\.(?:sv|vh)):(\d+)")


def failed_labels(log, srcdir=None):
    """Name each failed assertion: its label if it has one, otherwise the
    label comment (// spec_x) on its source line (in the run's own copy of the
    sources when srcdir is given)."""
    out = []
    hits = [(m.group(1).split(".")[-1], m.group(2), int(m.group(3))) for m in FAILED.finditer(log)]
    hits += [(m.group(1) or "", m.group(2), int(m.group(3))) for m in FAILED_ALT.finditer(log)]
    for label, fname, line in hits:
        if label.startswith("check_assert") or label.startswith("_witness_"):
            label = ""
        dirs = ([srcdir] if srcdir else []) + [os.path.join(J.ROOTS["FD"], "harness"),
                                               os.path.join(J.ROOTS["SNAP"], "formal")]
        for d in dirs:
            src = os.path.join(d, fname)
            if not label and os.path.exists(src):
                text = open(src).read().split("\n")
                if 0 < line <= len(text):
                    l = re.search(r"\b((?:spec|link|sanity|strengthen)_\w+):", text[line - 1]) or \
                        re.search(r"//\s*((?:spec|link|sanity|strengthen)_\w+)", text[line - 1])
                    label = l.group(1) if l else text[line - 1].strip()[:60]
        item = f"{label} ({fname}:{line})"
        if item not in out:
            out.append(item)
    return out


def cmd_run(args):
    rows = open(os.path.join(args.work, f"tasks-{args.cls}.tsv")).read().splitlines()
    name, job, engine, mode, depth, expect, timeout = rows[args.index].split("\t")
    workdir = os.path.join(args.work, "runs", name)
    os.makedirs(os.path.join(args.work, "results"), exist_ok=True)
    sby = os.path.join(os.environ.get("SBY_BIN", J.SBY_BIN), "sby")
    start = time.time()
    cmd = ["timeout", "--signal=TERM", "--kill-after=60", timeout, sby, "-f", "-d", workdir,
           os.path.join(args.work, "sby", name + ".sby")]
    print("+", " ".join(shlex.quote(c) for c in cmd), flush=True)
    rc = subprocess.call(cmd)
    wall = time.time() - start
    log = ""
    logfile = os.path.join(workdir, "logfile.txt")
    if os.path.exists(logfile):
        log = open(logfile, errors="replace").read()
    base, ind, frames, status = parse_log(log)
    if status is None:
        status = "TIMEOUT" if rc in (124, 137) else "ERROR"
    met = (status == "PASS") if expect == "PASS" else (status == "FAIL" and rc == 0)
    failed = failed_labels(log, os.path.join(workdir, "src"))
    result = {
        "task": name, "job": job, "engine": engine, "mode": mode, "depth": int(depth),
        "expect": expect, "status": status, "rc": rc, "expectation_met": met,
        "wall_s": round(wall, 1), "timeout_s": int(timeout),
        "slurm_job": os.environ.get("SLURM_ARRAY_JOB_ID", os.environ.get("SLURM_JOB_ID")),
        "slurm_task": os.environ.get("SLURM_ARRAY_TASK_ID"),
        "partition": os.environ.get("SLURM_JOB_PARTITION"),
        "node": os.environ.get("SLURMD_NODENAME"),
        "failed_assertions": failed,
        "base_steps": base, "induction_steps": ind, "abc_frames": frames,
        "summary": [l.split("] ", 1)[-1] for l in log.splitlines()
                    if re.search(r"summary:|DONE|Assert failed|failed assertion|reached cover|"
                                 r"Reached cover|Unreached cover|induction|Status:", l)][-40:],
    }
    with open(os.path.join(args.work, "results", name + ".json"), "w") as f:
        json.dump(result, f, indent=1)
    # Keep the work tree small: drop the copied sources and the model files
    # (traces and logs stay).
    subprocess.call(["rm", "-rf", os.path.join(workdir, "src"), os.path.join(workdir, "model")])
    print(json.dumps({k: result[k] for k in ("task", "status", "expectation_met", "wall_s")}))
    return 0


def cmd_summarize(args):
    # Several work trees may be given; when a task was rerun (e.g. after a
    # harness fix) the most recent result file wins.
    latest = {}
    for work in args.work:
        rdir = os.path.join(work, "results")
        if not os.path.isdir(rdir):
            continue
        for fn in sorted(os.listdir(rdir)):
            if fn.endswith(".json"):
                path = os.path.join(rdir, fn)
                r = json.load(open(path))
                r["_work"], r["_mtime"] = work, os.path.getmtime(path)
                if r["task"] not in latest or latest[r["task"]]["_mtime"] < r["_mtime"]:
                    latest[r["task"]] = r
    rows = [latest[k] for k in sorted(latest)]
    head = ["task", "status", "expect", "met", "wall_s", "deepest_step", "slurm", "partition",
            "failed_assertions", "run", "engine_verdict"]
    lines = ["\t".join(head)]
    curves = {}
    for r in rows:
        logfile = os.path.join(r["_work"], "runs", r["task"], "logfile.txt")
        verdict = ""
        if os.path.exists(logfile):  # re-parse with the current parser
            text = open(logfile, errors="replace").read()
            r["base_steps"], r["induction_steps"], r["abc_frames"], _ = parse_log(text)
            # The engine's own verdict, before sby's witness replay (which
            # fails for some AIGER counterexamples and turns FAIL into ERROR).
            v = re.findall(r"Status returned by engine(?: for \w+)?: (\w+)", text)
            verdict = ",".join(sorted(set(v)))
        base = {int(k): v for k, v in r["base_steps"].items()}
        ind = {int(k): v for k, v in r["induction_steps"].items()}
        frames = {int(k): v for k, v in r.get("abc_frames", {}).items()}
        deepest = max(base) if base else (max(frames) if frames else "")
        if r["status"] in ("TIMEOUT", "ERROR", "UNKNOWN") and base:
            deepest = f"{max(base) - 1} (started {max(base)})"
        slurm = f"{r['slurm_job']}_{r['slurm_task']}" if r.get("slurm_task") else str(r.get("slurm_job"))
        lines.append("\t".join(str(x) for x in [
            r["task"], r["status"], r["expect"], "yes" if r["expectation_met"] else "no",
            r["wall_s"], deepest, slurm, r.get("partition"),
            "; ".join(r.get("failed_assertions", [])), os.path.basename(r["_work"]), verdict]))
        if base or ind or frames:
            curves[r["task"]] = {"base_step_start_s": base, "induction_step_start_s": ind,
                                 "abc_frame_s": frames, "status": r["status"], "wall_s": r["wall_s"]}
    text = "\n".join(lines) + "\n"
    if args.tsv:
        open(args.tsv, "w").write(text)
    else:
        sys.stdout.write(text)
    if args.curves:
        json.dump(curves, open(args.curves, "w"), indent=1, sort_keys=True)


def cmd_curves(args):
    """Markdown table: seconds until the first d steps were all checked, per
    (job, engine), from sby's per-step log lines (smtbmc) or per-frame lines
    (abc bmc3). Engines without per-step output show only their total time at
    the full depth."""
    depths = [int(d) for d in args.depths.split(",")]
    latest = {}
    for work in args.work:
        rdir = os.path.join(work, "results")
        for fn in sorted(os.listdir(rdir)) if os.path.isdir(rdir) else []:
            r = json.load(open(os.path.join(rdir, fn)))
            if args.jobs and not re.search(args.jobs, r["job"]):
                continue
            logfile = os.path.join(work, "runs", r["task"], "logfile.txt")
            if os.path.exists(logfile):
                r["base_steps"], _, r["abc_frames"], _ = parse_log(open(logfile, errors="replace").read())
            latest[r["task"]] = r
    print("| job | engine | status | " + " | ".join(f"d={d}" for d in depths) + " |")
    print("|---|---|---|" + "---:|" * len(depths))
    for task in sorted(latest):
        r = latest[task]
        base = {int(k): v for k, v in r["base_steps"].items()}
        frames = {int(k): v for k, v in r.get("abc_frames", {}).items()}
        cells = []
        for d in depths:
            if d > r["depth"]:
                cells.append("")
            elif d in base:
                cells.append(str(base[d]))
            elif d == r["depth"] and r["status"] == "PASS":
                cells.append(f"{round(r['wall_s'])}*")
            elif (d - 1) in frames:
                cells.append(str(frames[d - 1]))
            else:
                cells.append("-")
        print(f"| {r['job']} | {r['engine']} | {r['status']} | " + " | ".join(cells) + " |")


def main():
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("plan"); a.add_argument("work"); a.add_argument("--only")
    a.add_argument("--class", dest="cls")
    a.add_argument("--engine", help="only engines matching this regex")
    a.add_argument("--timeout", type=int, help="override every task's timeout (s)")
    b = sub.add_parser("run"); b.add_argument("work"); b.add_argument("cls")
    b.add_argument("index", type=int)
    c = sub.add_parser("summarize"); c.add_argument("work", nargs="+"); c.add_argument("--tsv")
    c.add_argument("--curves")
    d = sub.add_parser("curves"); d.add_argument("work", nargs="+"); d.add_argument("--jobs")
    d.add_argument("--depths", default="10,20,30,40,50,60")
    args = p.parse_args()
    return {"plan": cmd_plan, "run": cmd_run, "summarize": cmd_summarize,
            "curves": cmd_curves}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
