#!/usr/bin/env bash
# Generate the named RTL variants of docs/notes/variants.md and their firmware images.
#
# Usage: scripts/gen_variants.sh [--publish DIR] [--no-firmware] [--no-check] [NAME...]
#   NAME           variants to generate (default: every configs/variants/*.json,
#                  in the order base rstreg cn cn_s2 diet4 diet2, then the rest)
#   --publish DIR  also copy each core to DIR/<name>.v and rewrite
#                  DIR/MANIFEST.sha256 (sha256sum format, one line per core)
#   --no-firmware  skip the firmware images
#   --no-check     skip the equivalence checks below
#
# Outputs (gitignored):
#   build/variants/<name>/protocol_emulator_core.v   module protocol_emulator_core,
#       header "// generated by scripts/generate.sh from hardcaml/ + configs/variants/<name>.json -- do not edit"
#   build/variants/<name>/firmware/<image>.{source,image}.json   the 19 built-in
#       images of firmware/, reassembled for the variant's architecture
#       (fifo_words) and shift restriction (assemble --variant), and the
#       source-file images of SOURCE_SET (uart-rx-idle, the flagship's engine 1):
#       firmware/<image>.source.json with its "architecture" set to the
#       variant's (copied unchanged when equal), assembled with --source
#       --variant. They need a 32-bit datapath; other variants do not get them.
#   build/variants/<name>/firmware/ext/<image>.image.json   for a variant with
#       options.line_unit: firmware/ext/*.source.json assembled for it
#       (docs/extension.md)
#
# Checks (unless --no-check), each fatal:
#   1. configs/instruction-sram-32.json regenerates src/protocol_emulator_core.v
#      byte for byte (written to a temporary file; src/ is never touched);
#   2. the base variant (no "options") equals src/protocol_emulator_core.v
#      except for the header line;
#   3. every variant whose firmware target equals the design of record
#      (fifo_words 8, barrel shifts) reproduces firmware/*.json byte for byte
#      (the built-in images and SOURCE_SET);
#   4. a variant with options.line_unit reproduces firmware/ext/*.image.json
#      byte for byte.
#
# Environment: DUNE_BUILD_DIR, DUNE_JOBS, OCAML_ENV as for scripts/generate.sh.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
abspath() { case "$1" in /*) printf '%s\n' "$1" ;; *) printf '%s\n' "$PWD/$1" ;; esac; }

PUBLISH="" FIRMWARE=1 CHECK=1 NAMES=()
while [ $# -gt 0 ]; do
  case "$1" in
    --publish) [ $# -ge 2 ] || { echo "gen_variants.sh: --publish needs a directory" >&2; exit 2; }
               PUBLISH=$(abspath "$2"); shift 2 ;;
    --no-firmware) FIRMWARE=0; shift ;;
    --no-check) CHECK=0; shift ;;
    -h|--help) sed -n '2,37p' "${BASH_SOURCE[0]}"; exit 0 ;;
    -*) echo "gen_variants.sh: unknown option $1" >&2; exit 2 ;;
    *) NAMES+=("$1"); shift ;;
  esac
done

if [ ${#NAMES[@]} -eq 0 ]; then
  for n in base rstreg cn cn_s2 diet4 diet2; do
    [ -f "$REPO/configs/variants/$n.json" ] && NAMES+=("$n")
  done
  for f in "$REPO"/configs/variants/*.json; do
    n=$(basename "$f" .json)
    case " ${NAMES[*]} " in *" $n "*) ;; *) NAMES+=("$n") ;; esac
  done
fi
for n in "${NAMES[@]}"; do
  [ -f "$REPO/configs/variants/$n.json" ] || { echo "gen_variants.sh: no configs/variants/$n.json" >&2; exit 2; }
done

BUILD_DIR=$(abspath "${DUNE_BUILD_DIR:-$REPO/hardcaml/_build}")
export DUNE_BUILD_DIR=$BUILD_DIR
JOBS=${DUNE_JOBS:-2}
if ! command -v dune >/dev/null 2>&1; then
  for env_file in "${OCAML_ENV:-}" "$REPO/scripts/ocaml-env.local.sh"; do
    if [ -n "$env_file" ] && [ -f "$env_file" ]; then
      # shellcheck disable=SC1090
      . "$env_file"
      break
    fi
  done
fi
command -v dune >/dev/null 2>&1 || { echo "gen_variants.sh: dune not found (see scripts/generate.sh)" >&2; exit 2; }
(cd "$REPO/hardcaml" && dune build --root . --build-dir "$BUILD_DIR" -j "$JOBS" \
  ./bin/generate_refinement.exe ./bin/assemble.exe)
ASSEMBLE=$BUILD_DIR/default/bin/assemble.exe

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

if [ "$CHECK" = 1 ]; then
  "$REPO/scripts/generate.sh" --output "$WORK/default.v" >/dev/null
  cmp -s "$WORK/default.v" "$REPO/src/protocol_emulator_core.v" || {
    echo "gen_variants.sh: CHECK FAILED: configs/instruction-sram-32.json no longer reproduces src/protocol_emulator_core.v" >&2
    exit 1; }
  echo "check: configs/instruction-sram-32.json reproduces src/protocol_emulator_core.v byte for byte"
fi

# The committed firmware images: file stem, built-in name, extra assembler arguments.
FIRMWARE_SET=(
  "uart-tx|uart-tx|" "uart-rx|uart-rx|"
  "spi-controller-mode0|spi-controller|--mode 0" "spi-controller-mode1|spi-controller|--mode 1"
  "spi-controller-mode2|spi-controller|--mode 2" "spi-controller-mode3|spi-controller|--mode 3"
  "spi-controller-fast|spi-controller|--mode 0 --half-period 16"
  "spi-target-mode0|spi-target|--mode 0" "spi-target-mode1|spi-target|--mode 1"
  "spi-target-mode2|spi-target|--mode 2" "spi-target-mode3|spi-target|--mode 3"
  "i2c-write|i2c-write|" "i2c-read|i2c-read|" "i2c-repeated-start|i2c-repeated-start|"
  "i2c-target-write|i2c-target-write|" "i2c-target-read|i2c-target-read|"
  "jtag|jtag|" "waveform|waveform|" "event-transmitter|event-transmitter|"
)
# Images kept only as source files (not OCaml built-ins) that the variant image
# sets also need: uart-rx-idle is engine 1 of firmware/flagship-scenario.json.
# The SWD, WS2812B, PS/2 and 1-Wire images are not reassembled: their tests
# load firmware/ directly and skip other designs (docs/firmware.md).
SOURCE_SET=(uart-rx-idle)

for n in "${NAMES[@]}"; do
  config=$REPO/configs/variants/$n.json
  out_dir=$REPO/build/variants/$n
  core=$out_dir/protocol_emulator_core.v
  "$REPO/scripts/generate.sh" --variant "$n" >/dev/null
  if [ "$CHECK" = 1 ] && [ "$n" = base ]; then
    if cmp -s <(tail -n +2 "$core") <(tail -n +2 "$REPO/src/protocol_emulator_core.v"); then
      echo "check: base equals src/protocol_emulator_core.v except the header line"
    else
      echo "gen_variants.sh: CHECK FAILED: base differs from src/protocol_emulator_core.v" >&2
      exit 1
    fi
  fi
  line="$n: $(sha256sum "$core" | cut -d' ' -f1) $(wc -l < "$core") lines"
  if [ "$FIRMWARE" = 1 ]; then
    fw=$out_dir/firmware
    rm -rf "$fw"
    mkdir -p "$fw"
    for entry in "${FIRMWARE_SET[@]}"; do
      IFS='|' read -r stem builtin extra <<< "$entry"
      # shellcheck disable=SC2086
      "$ASSEMBLE" --firmware "$builtin" $extra --variant "$config" \
        --output "$fw/$stem.image.json" --source-output "$fw/$stem.source.json" >/dev/null
    done
    line="$line; ${#FIRMWARE_SET[@]} firmware images"
    stems=()
    for entry in "${FIRMWARE_SET[@]}"; do stems+=("${entry%%|*}"); done
    if python3 - "$config" <<'EOF'
import json, sys
sys.exit(0 if json.load(open(sys.argv[1]))["architecture"]["data_width"] == 32 else 1)
EOF
    then
      for stem in "${SOURCE_SET[@]}"; do
        python3 - "$REPO/firmware/$stem.source.json" "$config" "$fw/$stem.source.json" <<'EOF'
import json, shutil, sys
source_path, config_path, out_path = sys.argv[1:]
source = json.load(open(source_path))
architecture = json.load(open(config_path))["architecture"]
if source["architecture"] == architecture:
    shutil.copyfile(source_path, out_path)   # unchanged, byte for byte
else:
    source["architecture"] = architecture
    with open(out_path, "w") as f:
        f.write(json.dumps(source, indent=2) + "\n")
EOF
        "$ASSEMBLE" --source "$fw/$stem.source.json" --variant "$config" \
          --output "$fw/$stem.image.json" >/dev/null
        stems+=("$stem")
      done
      line="$line + ${#SOURCE_SET[@]} from source"
    else
      line="$line (no source-file images: the datapath is not 32 bits)"
    fi
    same=1
    for stem in "${stems[@]}"; do
      for kind in source image; do
        cmp -s "$fw/$stem.$kind.json" "$REPO/firmware/$stem.$kind.json" || same=0
      done
    done
    if [ "$same" = 1 ]; then
      line="$line (identical to firmware/)"
    elif [ "$CHECK" = 1 ] && python3 - "$config" <<'EOF'
import json, sys
c = json.load(open(sys.argv[1]))
same_target = c["architecture"]["fifo_words"] == 8 and c.get("options", {}).get("shift", "barrel") == "barrel"
sys.exit(0 if same_target else 1)
EOF
    then
      echo "gen_variants.sh: CHECK FAILED: $n targets the design-of-record firmware but its images differ from firmware/" >&2
      exit 1
    fi
  fi
  if [ "$FIRMWARE" = 1 ] && python3 - "$config" <<'EOF'
import json, sys
sys.exit(0 if json.load(open(sys.argv[1])).get("options", {}).get("line_unit", "none") != "none" else 1)
EOF
  then
    ext=$out_dir/firmware/ext
    mkdir -p "$ext"
    count=0 same=1
    for src in "$REPO"/firmware/ext/*.source.json; do
      stem=$(basename "$src" .source.json)
      "$ASSEMBLE" --source "$src" --variant "$config" --output "$ext/$stem.image.json" >/dev/null
      cmp -s "$ext/$stem.image.json" "$REPO/firmware/ext/$stem.image.json" || same=0
      count=$((count + 1))
    done
    if [ "$same" = 1 ]; then
      line="$line; $count line-unit images (identical to firmware/ext/)"
    elif [ "$CHECK" = 1 ]; then
      echo "gen_variants.sh: CHECK FAILED: $n does not reproduce firmware/ext/*.image.json" >&2
      exit 1
    else
      line="$line; $count line-unit images (DIFFER from firmware/ext/)"
    fi
  fi
  echo "$line"
done

if [ -n "$PUBLISH" ]; then
  mkdir -p "$PUBLISH"
  for n in "${NAMES[@]}"; do
    cp "$REPO/build/variants/$n/protocol_emulator_core.v" "$PUBLISH/$n.v.tmp"
    chmod 644 "$PUBLISH/$n.v.tmp"
    mv "$PUBLISH/$n.v.tmp" "$PUBLISH/$n.v"
  done
  # Rewrite the manifest from every published core (other names are kept).
  (cd "$PUBLISH" && sha256sum -- *.v > MANIFEST.sha256.tmp && mv MANIFEST.sha256.tmp MANIFEST.sha256)
  echo "published ${#NAMES[@]} cores to $PUBLISH (MANIFEST.sha256)"
fi
