#!/usr/bin/env bash
# Regenerate src/protocol_emulator_core.v from the Hardcaml sources in hardcaml/.
#
# Usage: scripts/generate.sh [CONFIG_JSON]
#   CONFIG_JSON  default configs/instruction-sram-32.json. A refinement config
#                (schema protocol-emulator.refinement.v1) uses the SRAM
#                generator; an architecture config uses the register-store one.
#
# Environment:
#   OUTPUT          output file (default src/protocol_emulator_core.v)
#   DUNE_BUILD_DIR  dune build directory (default hardcaml/_build)
#   DUNE_JOBS       dune parallelism (default 2)
#   OCAML_ENV       optional shell file to source when dune is not on PATH
#                   (a local, gitignored scripts/ocaml-env.local.sh is also tried)
#
# CI (.github/workflows/regen.yaml) runs this script and fails if the committed
# src/protocol_emulator_core.v differs from the regenerated file.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
MODULE_NAME=protocol_emulator_core

abspath() { case "$1" in /*) printf '%s\n' "$1" ;; *) printf '%s\n' "$PWD/$1" ;; esac; }

CONFIG=$(abspath "${1:-$REPO/configs/instruction-sram-32.json}")
OUTPUT=$(abspath "${OUTPUT:-$REPO/src/protocol_emulator_core.v}")
BUILD_DIR=$(abspath "${DUNE_BUILD_DIR:-$REPO/hardcaml/_build}")
JOBS=${DUNE_JOBS:-2}

[ -f "$CONFIG" ] || { echo "generate.sh: config not found: $CONFIG" >&2; exit 2; }

if ! command -v dune >/dev/null 2>&1; then
  for env_file in "${OCAML_ENV:-}" "$REPO/scripts/ocaml-env.local.sh"; do
    if [ -n "$env_file" ] && [ -f "$env_file" ]; then
      # shellcheck disable=SC1090
      . "$env_file"
      break
    fi
  done
fi
command -v dune >/dev/null 2>&1 || {
  echo "generate.sh: dune not found; install the pinned opam packages (see scripts/opam-deps.txt) or set OCAML_ENV" >&2
  exit 2
}

if grep -q '"protocol-emulator.refinement.v1"' "$CONFIG"; then
  GENERATOR=generate_refinement
else
  GENERATOR=generate
fi

# Path recorded in the header: repository-relative when possible, so the
# output is identical on every machine.
case "$CONFIG" in
  "$REPO"/*) CONFIG_LABEL=${CONFIG#"$REPO"/} ;;
  *) CONFIG_LABEL=$(basename "$CONFIG") ;;
esac

# dune interprets targets relative to the current directory, so build from
# the Hardcaml project root.
(cd "$REPO/hardcaml" && dune build --root . --build-dir "$BUILD_DIR" -j "$JOBS" \
  "./bin/$GENERATOR.exe")

TMP=$(mktemp "${OUTPUT}.XXXXXX")
trap 'rm -f "$TMP" "$TMP.body"' EXIT
"$BUILD_DIR/default/bin/$GENERATOR.exe" --config "$CONFIG" --output "$TMP.body" \
  --name "$MODULE_NAME"
{
  printf '// generated by scripts/generate.sh from hardcaml/ + %s -- do not edit\n' "$CONFIG_LABEL"
  cat "$TMP.body"
} > "$TMP"
chmod 644 "$TMP"
mv "$TMP" "$OUTPUT"
echo "generate.sh: wrote $OUTPUT ($GENERATOR, $CONFIG_LABEL, module $MODULE_NAME)"
