#!/usr/bin/env bash
# Check that the committed 6x4 core, variants6x4/protocol_emulator_core.v, is
# what hardcaml/ + configs/variants/diet4.json generate now.
#
# Usage: variants6x4/check_core.sh [--update]
#   --update   overwrite the committed core with the fresh generation instead
#              of failing (then review and commit it)
#
# The generation runs scripts/generate.sh with the variant config and a
# temporary output, exactly as scripts/gen_variants.sh does for
# build/variants/diet4/, so src/ and build/ are never written. It needs the
# pinned OCaml toolchain (scripts/opam-deps.txt; DUNE_BUILD_DIR, DUNE_JOBS and
# OCAML_ENV as for scripts/generate.sh). CI: .github/workflows/gds_6x4.yaml,
# job core_current.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
COMMITTED=$REPO/variants6x4/protocol_emulator_core.v
CONFIG=$REPO/configs/variants/diet4.json
UPDATE=0
case "${1:-}" in
  --update) UPDATE=1 ;;
  "") ;;
  *) echo "check_core.sh: unknown argument $1" >&2; exit 2 ;;
esac

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
"$REPO/scripts/generate.sh" "$CONFIG" --output "$TMP/protocol_emulator_core.v"

want='// generated by scripts/generate.sh from hardcaml/ + configs/variants/diet4.json -- do not edit'
got=$(head -n 1 "$TMP/protocol_emulator_core.v")
[ "$got" = "$want" ] || { echo "check_core.sh: unexpected header: $got" >&2; exit 1; }

fresh=$(sha256sum "$TMP/protocol_emulator_core.v" | cut -d' ' -f1)
committed=$(sha256sum "$COMMITTED" | cut -d' ' -f1)
echo "check_core.sh: fresh     $fresh"
echo "check_core.sh: committed $committed  variants6x4/protocol_emulator_core.v"
if [ "$fresh" = "$committed" ]; then
  echo "check_core.sh: PASS, the committed 6x4 core is current with hardcaml/ + configs/variants/diet4.json"
  exit 0
fi
if [ "$UPDATE" = 1 ]; then
  cp "$TMP/protocol_emulator_core.v" "$COMMITTED"
  chmod 644 "$COMMITTED"
  echo "check_core.sh: updated variants6x4/protocol_emulator_core.v; update PROVENANCE.json and re-run the 6x4 signoff (docs/6x4.md)"
  exit 0
fi
diff -u "$COMMITTED" "$TMP/protocol_emulator_core.v" | head -n 40 || true
echo "check_core.sh: FAIL, variants6x4/protocol_emulator_core.v is stale; run variants6x4/check_core.sh --update" >&2
exit 1
