#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Switch a checkout of this repository to the 6x4 (diet4) submission build.

  variants6x4/switch.py check          verify the overlay against the checkout; write nothing
  variants6x4/switch.py apply          check, then rewrite the three submission inputs in place
  variants6x4/switch.py apply --dry-run

`apply` changes exactly three files, and nothing else:

  src/protocol_emulator_core.v  <- variants6x4/protocol_emulator_core.v (the generated diet4 core;
                                   module protocol_emulator_core, so src/project.v is unchanged)
  src/config.json               <- src/config.json with variants6x4/config.overlay.json applied as an
                                   RFC 7386 JSON merge patch (objects merge, other values replace,
                                   null deletes). The file is read with json.load, as tt-support-tools
                                   reads it, so its repeated "//" comment keys collapse to one.
  info.yaml                     <- info.yaml with the scalar project keys of variants6x4/info.overlay.json
                                   replaced in place (the tiles line, value and trailing comment);
                                   every other line is unchanged

It is meant for a CI workspace (.github/workflows/gds_6x4.yaml) or for a
deliberate switch of the submission (docs/6x4.md, "Switching the submission").
`check` fails when:

  * the committed core's sha256 differs from PROVENANCE.json, or its header does
    not name configs/variants/diet4.json;
  * the overlay would add a top-level key that src/config.json lacks, other than
    the keys listed in PROVENANCE.json "overlay_new_keys";
  * the overlay's MACROS instance names differ from src/config.json's;
  * the checkout is already switched (src core header names a variant config);
  * the merged config leaves a row segment without a lattice stripe
    (variants6x4/row_islands.py: a short power strap, which fails the precheck).

Standard library only (Python 3.8+).
"""

import argparse
import copy
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.dont_write_bytecode = True
import row_islands  # noqa: E402

CORE_SRC = os.path.join(HERE, "protocol_emulator_core.v")
CONFIG_OVERLAY = os.path.join(HERE, "config.overlay.json")
INFO_OVERLAY = os.path.join(HERE, "info.overlay.json")
PROVENANCE = os.path.join(HERE, "PROVENANCE.json")
HEADER = "// generated by scripts/generate.sh from hardcaml/ + configs/variants/diet4.json -- do not edit"


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def merge_patch(target, patch):
    """RFC 7386 JSON merge patch."""
    if not isinstance(patch, dict):
        return copy.deepcopy(patch)
    out = copy.deepcopy(target) if isinstance(target, dict) else {}
    for k, v in patch.items():
        if v is None:
            out.pop(k, None)
        else:
            out[k] = merge_patch(out.get(k), v)
    return out


def load_overlay(path):
    with open(path) as f:
        ov = json.load(f)
    ov.pop("//", None)  # documentation only; never applied
    return ov


def edit_info(text, project_keys, comments=None):
    """Replace the value (and, if given, the trailing comment) of scalar project keys in place."""
    comments = comments or {}
    for key, value in project_keys.items():
        if not isinstance(value, (str, int, float)) or isinstance(value, bool):
            raise SystemExit("info overlay: only scalar project keys are supported (%s)" % key)
        rendered = '"%s"' % value if isinstance(value, str) else str(value)
        pat = re.compile(r'^(\s+%s:\s*)("[^"]*"|[^\s#]+)([ \t]*)(#.*)?$' % re.escape(key), re.M)

        def repl(m):
            line = m.group(1) + rendered
            if key in comments:
                return line + (m.group(3) or "  ") + "# " + comments[key]
            return line + (m.group(3) or "") + (m.group(4) or "")
        text, n = pat.subn(repl, text, count=1)
        if n != 1:
            raise SystemExit("info.yaml: no '%s:' line under project" % key)
    return text


def plan(repo):
    """Return (errors, notes, outputs) where outputs maps repo paths to new contents (bytes)."""
    errors, notes = [], []
    prov = json.load(open(PROVENANCE))
    src_core = os.path.join(repo, "src", "protocol_emulator_core.v")
    src_cfg_path = os.path.join(repo, "src", "config.json")
    info_path = os.path.join(repo, "info.yaml")

    # -- core
    have = sha256(CORE_SRC)
    if have != prov["core_sha256"]:
        errors.append("variants6x4/protocol_emulator_core.v sha256 %s != PROVENANCE.json %s"
                      % (have, prov["core_sha256"]))
    with open(CORE_SRC) as f:
        head = f.readline().rstrip("\n")
        second = f.readline()
    if head != HEADER or not second.startswith("module protocol_emulator_core"):
        errors.append("variants6x4/protocol_emulator_core.v: unexpected header/module line")
    with open(src_core) as f:
        cur_head = f.readline().rstrip("\n")
    if "configs/variants/" in cur_head:
        errors.append("src/protocol_emulator_core.v is already a variant core (%s); switch a clean checkout"
                      % cur_head)
    notes.append("core: %s (sha256 %s) replaces src/protocol_emulator_core.v (%s)"
                 % (os.path.relpath(CORE_SRC, REPO), have[:12], sha256(src_core)[:12]))

    # -- config
    with open(src_cfg_path) as f:
        base_cfg = json.load(f)
    ov = load_overlay(CONFIG_OVERLAY)
    allowed_new = set(prov.get("overlay_new_keys", []))
    for k in ov:
        if k not in base_cfg and k not in allowed_new:
            errors.append("config overlay adds %s, which src/config.json does not have "
                          "(list it in PROVENANCE.json overlay_new_keys if intended)" % k)
    for macro, spec in ov.get("MACROS", {}).items():
        base_insts = set(base_cfg.get("MACROS", {}).get(macro, {}).get("instances", {}))
        ov_insts = set(spec.get("instances", {}))
        if ov_insts != base_insts:
            errors.append("MACROS %s: overlay instances %s != src/config.json %s"
                          % (macro, sorted(ov_insts ^ base_insts), sorted(base_insts)))
    merged = merge_patch(base_cfg, ov)
    changed = sorted(k for k in set(base_cfg) | set(merged)
                     if k != "//" and base_cfg.get(k, "<unset>") != merged.get(k, "<unset>"))
    notes.append("config: keys changed by the overlay: %s" % ", ".join(changed))

    # -- info.yaml
    info_ov = load_overlay(INFO_OVERLAY)
    with open(info_path) as f:
        info_text = f.read()
    info_new = edit_info(info_text, info_ov.get("project", {}), info_ov.get("project_comments", {}))
    tiles = re.search(r'^\s+tiles:\s*"([^"]+)"', info_new, re.M).group(1)
    notes.append("info.yaml: tiles %s -> %s"
                 % (re.search(r'^\s+tiles:\s*"([^"]+)"', info_text, re.M).group(1), tiles))

    # -- short power straps (tool-free model of CutRows + GeneratePDN)
    core, n_rows = row_islands.core_box(tiles)
    macros = row_islands.macros_from_config(merged, os.path.join(repo, "src"))
    strp = row_islands.stripes(merged, core)
    hh = row_islands.dbu(merged.get("FP_MACRO_HORIZONTAL_HALO", row_islands.DEFAULT_HALO))
    vh = row_islands.dbu(merged.get("FP_MACRO_VERTICAL_HALO", row_islands.DEFAULT_HALO))
    isl = row_islands.islands(core, n_rows, macros, strp, hh, vh, row_islands.obstructions(merged))
    if isl:
        errors.append("merged config: %d row segment(s) without a lattice stripe in %d channel(s) "
                      "(short power straps; variants6x4/row_islands.py)" % (len(isl), len(row_islands.channels(isl))))
    else:
        notes.append("row islands: 0 at %s with halo %.2f/%.2f um (no short power strap predicted)"
                     % (tiles, row_islands.um(hh), row_islands.um(vh)))

    outputs = {
        "src/protocol_emulator_core.v": open(CORE_SRC, "rb").read(),
        "src/config.json": (json.dumps(merged, indent=2) + "\n").encode(),
        "info.yaml": info_new.encode(),
    }
    return errors, notes, outputs


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("action", choices=("check", "apply"))
    ap.add_argument("--repo", default=REPO, help="checkout to switch (default: this one)")
    ap.add_argument("--dry-run", action="store_true", help="with apply: report, write nothing")
    args = ap.parse_args()
    errors, notes, outputs = plan(os.path.abspath(args.repo))
    for n in notes:
        print("INFO " + n)
    for e in errors:
        print("FAIL " + e)
    if errors:
        print("RESULT FAIL: %d problem(s); nothing written" % len(errors))
        return 1
    if args.action == "apply" and not args.dry_run:
        for rel, data in outputs.items():
            path = os.path.join(args.repo, rel)
            tmp = path + ".tmp-6x4"
            with open(tmp, "wb") as f:
                f.write(data)
            os.replace(tmp, path)
            print("WROTE %s (sha256 %s)" % (rel, hashlib.sha256(data).hexdigest()[:12]))
        print("RESULT PASS: checkout switched to the 6x4 diet4 build")
    else:
        print("RESULT PASS: overlay consistent with this checkout%s"
              % (" (dry run, nothing written)" if args.action == "apply" else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
